[package]
name = "transform_wechat_areainfo"
version = "0.1.0"
authors = ["ilovelll <gradle@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"